name: Areas CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  # testing on Ubuntu
  test_ubuntu:
    name: Testing on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: python -m unittest testAreas.py
      #    pytest testAreas.py
        
    
  # testing on Windows
#   test_windows:
#     name: Testing on Windows
#     runs-on: windows-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.10
#       uses: actions/setup-python@v2
#       with:
#         python-version: "3.10"

#     - name: Test with unittest
#       run: |
#         pytest testAreas.py
        
#   # testing on MACOS
#   test_macos:
#     name: Testing on MacOS
#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.10
#       uses: actions/setup-python@v2
#       with:
#         python-version: "3.10"

#     - name: Test with unittest
#       run: |
#         pytest testAreas.py

        
        
