name: Areas CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  # testing on Ubuntu
  test_ubuntu:
    name: Testing on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Test with unittest
      run: |
        pytest testAreas.py
    
  # testing on Windows
  test_windows:
    name: Testing on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Test with unittest
      run: |
        pytest testAreas.py
        
  # testing on MACOS
  test_macos:
    name: Testing on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Test with unittest
      run: |
        pytest testAreas.py

        
        
